### ISSUE TITLE
Exploration of supporting single-dispatched functions for argname()

### ISSUE THREAD

**Issue by pwwang** [pwwang/python-varname#53]
```python
>>> from varname import argname
>>> from functools import singledispatch
>>> 
>>> @singledispatch
... def add(a, b):
...     ...
... 
>>> @add.register(int)
... def _(a, b):
...     aname = argname(a, b)
...     print(aname)
...     return a + b 
... 
>>> def mul(a, b):
...     aname = argname(a, b)
...     print(aname)
...     return a * b
... 
>>> x = y = 1
>>> 
>>> mul(x, y)
('x', 'y')
1
>>> 
>>> add(x, y)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    add(x, y)
  File "/.../lib/python3.7/functools.py", line 840, in wrappe
r
    return dispatch(args[0].__class__)(*args, **kw)
  File "<input>", line 3, in _
    aname = argname(a, b)
  File "/.../varname/core.py", line 401, in argnam
e
    f"No value passed for argument {argnode.id!r}, "
ValueError: No value passed for argument 'a', or it is not an argument at all.

**Comment by pwwang** [comment]
@https://github.com/pwwang/python-varname/commit/753e39090b20857a99f0571976546e4d0a35c4d9

```python
>>> from varname import argname
>>> from functools import singledispatch
>>> 
>>> @singledispatch
... def add(a, b):
...     ...
... 
>>> @add.register(int)
... def add_int(a, b):
...     aname = argname(a, b, func=add_int)
...     print(aname)
...     return a + b 
... 
>>> @add.register(str)
... def add_str(a, b):
...     aname = argname(a, b, dispatch=str) # specify a type
...     print(aname)
...     return a + b 
... 
>>> x = y = 1
>>> p = q = 'a'
>>> 
>>> add(x, y)
('x', 'y')
2
>>> add(p, q)
('p', 'q')
'aa'

**Comment by pwwang** [comment]
Close via [v0.7.0](https://github.com/pwwang/python-varname/releases/tag/0.7.0)
