### ISSUE TITLE
Failure to find parent assign node doesn't mean improper use

### ISSUE THREAD

**Issue by pwwang** [pwwang/python-varname#60]
https://github.com/pwwang/python-varname/blob/d3182fd1deefc89c079100de986fdf5034616c5e/varname/core.py#L107-L137

The `ImproperUseError` (last line) might be misleading if the `node` passed to `lookfor_parent_assign()` is the wrong one (i.e. wrong `frame` or `ignore` passed).

An example:

```python
def decor(f):
    def wrapper():
        return f()
    return wrapper

def func():
    return varname(ignore=(func2, 0)) # saying func2 is not decorated, but it actually is

@decor
def func2():
    return func()

var = func2()
```

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    var = func2()
  File "<input>", line 3, in wrapper
    return f()
  File "<input>", line 3, in func2
    return func()
  File "<input>", line 2, in func
    return varname(ignore=(func2, 0)) # saying func2 is not decorated, but it actually is
  File "/home/pwwang/github/python-varname/varname/core.py", line 129, in varname
    strict=False,
  File "/home/pwwang/github/python-varname/varname/core.py", line 137, in varname
    raise ImproperUseError(msg)
varname.utils.ImproperUseError: Expression is not part of an assignment.
```

It is indeed an `ImproperUseError` since `ignore` refers to `return func()` inside `func2`. However, it is still confusing, as people may be expecting the line `var = func2()`. We should either indicate the place where the `ImproperUseError` happens, or raise a general error (say `VarnameRetrievingError`) and indicating that it may be due to improper use, or locating of a wrong node. 

I prefer the former way.

This also applies to the other `ImportUseError` for `multi_vars=False` but multiple variables on LHS.

@breuleux

**Comment by pwwang** [comment]
Commit https://github.com/pwwang/python-varname/commit/923357901ae107b533306941c1598ca2f3c2b09f now is giving a richer message in this case:

```python console
---------------------------------------------------------------------------
ImproperUseError                          Traceback (most recent call last)
/tmp/ipykernel_14037/1145745146.py in <module>
     13     return func()
     14 
---> 15 var = func2()

/tmp/ipykernel_14037/1145745146.py in wrapper()
      3 def decor(f):
      4     def wrapper():
----> 5         return f()
      6     return wrapper
      7 

/tmp/ipykernel_14037/1145745146.py in func2()
     11 @decor
     12 def func2():
---> 13     return func()
     14 
     15 var = func2()

/tmp/ipykernel_14037/1145745146.py in func()
      7 
      8 def func():
----> 9     return varname(ignore=(func2, 0)) # saying func2 is not decorated, but it actually is
     10 
     11 @decor

~/github/python-varname/varname/core.py in varname(frame, ignore, multi_vars, raise_exc, strict)
    128                 multi_vars=multi_vars,
    129                 raise_exc=raise_exc,
--> 130                 strict=False,
    131             )
    132 

~/github/python-varname/varname/core.py in varname(frame, ignore, multi_vars, raise_exc, strict)
    136             else:
    137                 msg = "Expression is not part of an assignment."
--> 138             raise ImproperUseError(rich_exc_message(msg, refnode))
    139         return None
    140 

ImproperUseError: Expression is not part of an assignment.

  /tmp/ipykernel_14037/1145745146.py:14:12
    | 12  @decor
    | 13  def func2():
  > | 14      return func()
    |                ^
```
