### ISSUE TITLE
Error retrieving value for `__setitem__`

### ISSUE THREAD

**Issue by edward-io** [pwwang/python-varname#78]
Really cool library! I'm attempting to override a dict to capture the variable names passed as values.

Inside a file:

```
from collections import UserDict
import varname

class MyDict(UserDict):
    def __init__(self, *args, **kwargs):
        # print(varname.argname("args"), varname.argname("kwargs"))
        super().__init__(*args, **kwargs)
    
    def __setitem__(self, key, value):
        print(varname.argname("value"))
        super().__setitem__(key, value)

x = "my_value"
d = MyDict()
d['x'] = x
```

Expected output: `x`

Actual output:

```
Traceback (most recent call last):
  File "/Users/edward/temp/mutmap.py", line 15, in <module>
    d['x'] = value
  File "/Users/edward/temp/mutmap.py", line 10, in __setitem__
    print(varname.argname("value"))
  File "/Users/edward/temp/python-varname/varname/core.py", line 391, in argname
    func_node = get_node_by_frame(func_frame)
  File "/Users/edward/temp/python-varname/varname/utils.py", line 141, in get_node_by_frame
    raise VarnameRetrievingError(
varname.utils.VarnameRetrievingError: Couldn't retrieve the call node. This may happen if you're using some other AST magic at the same time, such as pytest, ipython, macropy, or birdseye.
```

**Comment by pwwang** [comment]
Currently, only a `Call` node is supported to retrieve the arguments.

So a temporary solution is:

```python
d.__setitem__("x", x)
```

Will explore if we could adopt an `Assignment`.

**Comment by pwwang** [comment]
Since `STORE_ATTR` and `STORE_SUBSCR` are not going to be supported by executing, this will not be in the recent plan (even though it may be implemented using `executing.Source.executing(frame).statements`).

**Comment by pwwang** [comment]
STORE_ATTR and STORE_SUBSCR are supported by executing at 0.9.0. This will be implemented later.

**Comment by pwwang** [comment]
This is supported by [`v0.9.0`](https://github.com/pwwang/python-varname/releases/tag/0.9.0).

**Comment by edward-io** [comment]
Thank you so much!
