### ISSUE TITLE
argname seems not working

### ISSUE THREAD

**Issue by cinntamani** [pwwang/python-varname#80]
Hello,

I have a very simple test case, and I am not sure why argname does not work. Please let me know if I am missing something very basic.

The code is as follows:
```
import varname

def simple_fn(obj):
    return varname.argname(obj)

if __name__ == '__main__':
    class Missing:
        pass

    a = Missing()
    assert simple_fn(a) == 'a'

```
If I run in the terminal, I get the following error:
```
Traceback (most recent call last):
  File "temp.py", line 12, in <module>
    assert simple_fn(a) == 'a'
  File "temp.py", line 5, in simple_fn
    return varname.argname(obj)
  File "miniconda3/envs/py/lib/python3.10/site-packages/varname/core.py", line 432, in argname
    match = re.match(r"^([\w_]+)\[(.+)\]$", farg)
  File "miniconda3/envs/py/lib/python3.10/re.py", line 190, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```

Thank you!

**Comment by cinntamani** [comment]
Thank you! This is very magical indeed.
